Addition of Roadmap
RitikPatni/Front-End-Web-Development-Resources pull request #107
Opened 2020-10-06 19:09 UTC by stuti-ui

2020-10-11 12:04 UTC, stuti-ui commented
@RitikPatni kindly look #107

2020-10-11 16:21 UTC, RitikPatni requested changes

2020-10-11 17:28 UTC, stuti-ui commented on README.md
> +## Roadmap
Changes done. Kindly review it once again.

2020-10-12 04:25 UTC, RitikPatni commented on README.md
> +## Roadmap
This looks much clear now. Thanks for the contribution.

2020-10-12 04:25 UTC, merged

2020-10-12 06:19 UTC, stuti-ui commented
Thank you.

On Mon, Oct 12, 2020 at 9:56 AM Ritik Patni <notifications@github.com>
wrote:

> Merged #107
> <https://github.com/RitikPatni/Front-End-Web-Development-Resources/pull/107>
> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RitikPatni/Front-End-Web-Development-Resources/pull/107#event-3864617530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APXYEICLHWWUNMVICIHEYQDSKKANXANCNFSM4SGN6GHQ>
> .
>